apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: septa-slackbot
  labels: {app: septa-slackbot}
spec:
  replicas: 1
  template:
    metadata: {labels: {app: septa-slackbot}}
    spec:
      containers:
      - name: septa-slackbot
        image: ajt89/septa-slackbot:active
        ports:
          - containerPort: 8080
        env:
          - name: SLACK_TOKEN
            valueFrom:
              secretKeyRef:
                name: septa-slackbot-secret
                key: SLACK_TOKEN

